version: '3.8'

services:
  wireguard:
    image: linuxserver/wireguard
    container_name: wireguard
    restart: unless-stopped
    volumes:
      - './wireguard:/config'
      - '/lib/modules:/lib/modules:ro'
    environment:
      - PUID=1000
      - PGID=1000
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    privileged: true
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=0
    networks:
      - backbone

  telegram_bot:
    build:
      context: .
    container_name: TG_BOT
    restart: unless-stopped
    network_mode: service:wireguard
    depends_on:
      - wireguard

networks:
  backbone:
    driver: bridge